---
- name: Installing nginx
  hosts: dockerservers
  remote_user: ansible_remote
  sudo: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        pkg: nginx
        state: present
